-- V4__create_table_rooms.sql
CREATE TABLE rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    number INTEGER NOT NULL,
    price DECIMAL(7,2) NOT NULL,
    capacity INTEGER NOT NULL,
    hotel_id BIGINT NOT NULL,

    CONSTRAINT fk_rooms_hotel
            FOREIGN KEY (hotel_id)
            REFERENCES hotels (id)
            ON DELETE CASCADE
);